Fix PHPStan issues and disable Psalm due to dropped support in CakePHP 5.3.x

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -93,9 +93,9 @@ jobs:
       - name: Run PHP CodeSniffer
         run: vendor/bin/phpcs --report=checkstyle | cs2pr
 
-      - name: Run psalm
-        if: success() || failure()
-        run: vendor/bin/psalm.phar --output-format=github
+#      - name: Run psalm
+#        if: success() || failure()
+#        run: vendor/bin/psalm.phar --output-format=github
 
       - name: Run phpstan
         if: success() || failure()
